heat_template_version: 2013-05-23

description: The Heat Orchestration template used for the creation and provisioning of a stack.

parameters:
  InstanceType:
    description: The type of the instance to provision.
    type: string
    default: m1.small
  ImageId:
    description: The id of the image to provision.
    type: string
    default: cedarish
  KeyName:
    description: The name of an already defined key pair in OpenStack, used for enabling SSH access to the web server.
    type: string
    default: openstackkeypair

resources:
  Server:
    type: AWS::EC2::Instance
    properties:
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      ImageId: {Ref: ImageId}
  IP:
    type: AWS::EC2::EIP
  IP_Assoc:
    type: AWS::EC2::EIPAssociation
    properties:
      EIP: {Ref: IP}
      InstanceId: {Ref: Server}

outputs:
  KP_Out:
    description: Key pair name
    value: {Ref: KeyName}
  IP_Out:
    description: IP Address of the access host
    value: {Ref: IP}
